# House Prices

In [11]:
import pandas as pd
import numpy as np

In [12]:
data = pd.read_csv("houseprice.csv")
data.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities    ...     PoolArea PoolQC Fence MiscFeature MiscVal  \
0         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
1         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
2         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
3         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
4         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   

  MoSold YrSold  SaleType  SaleCondition  SalePrice  
0      2   2008        WD         Normal     208500  
1      5   2007        WD         Normal     181500  
2      9   2008        WD         Normal     223500  
3      2   2006        WD        Abnorml     140000  
4     12   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [13]:
data.shape

(1460, 81)

In [14]:
#SalePrice --> bağımlı, hedef değişken
columns=["OverallQual","TotalBsmtSF","1stFlrSF","GrLivArea","WoodDeckSF","BsmtUnfSF",
    "LotFrontage","MasVnrArea","GarageYrBlt","SalePrice"]

In [15]:
data=pd.read_csv("houseprice.csv", usecols=columns)
print(data.shape)
data.head()

(1460, 10)


LotFrontage  OverallQual  MasVnrArea  BsmtUnfSF  TotalBsmtSF  1stFlrSF  \
0         65.0            7       196.0        150          856       856   
1         80.0            6         0.0        284         1262      1262   
2         68.0            7       162.0        434          920       920   
3         60.0            7         0.0        540          756       961   
4         84.0            8       350.0        490         1145      1145   

   GrLivArea  GarageYrBlt  WoodDeckSF  SalePrice  
0       1710       2003.0           0     208500  
1       1262       1976.0         298     181500  
2       1786       2001.0           0     223500  
3       1717       1998.0           0     140000  
4       2198       2000.0         192     250000

In [16]:
null_columns=[]

def findNullColumns(df):
    global null_columns
    null_columns=[]
    for col in df.columns:
        col_sum=df[col].isnull().sum()
        if col_sum!=0:
            null_columns.append(col)

In [17]:
findNullColumns(data)
null_columns

['LotFrontage', 'MasVnrArea', 'GarageYrBlt']

In [18]:
col_zero=[]
for col in data.columns:
    if col in null_columns:
        col_zero.append(col+"_zero")
    else:
        col_zero.append(col)

In [19]:
col_zero

['LotFrontage_zero',
 'OverallQual',
 'MasVnrArea_zero',
 'BsmtUnfSF',
 'TotalBsmtSF',
 '1stFlrSF',
 'GrLivArea',
 'GarageYrBlt_zero',
 'WoodDeckSF',
 'SalePrice']

In [20]:
col_zero.pop()

'SalePrice'

In [21]:
col_median=[]
for col in data.columns:
    if col in null_columns:
        col_median.append(col+"_median")
    else:
        col_median.append(col)

In [22]:
col_median.pop()

'SalePrice'

In [23]:
from sklearn.model_selection import train_test_split

# X_train = matris -> büyük harfle,  y_train = vektör -> küçük harfle
X_train, X_test, y_train, y_test = train_test_split(data.drop(columns=["SalePrice"]), 
                                                    data.SalePrice, test_size=0.3, random_state=0)
X_train.shape, X_test.shape

((1022, 9), (438, 9))

In [24]:
findNullColumns(X_train)
null_columns

['LotFrontage', 'MasVnrArea', 'GarageYrBlt']

In [25]:
def fillNullColumns(df):
    for var in null_columns:
        median = df[var].median()
        df[var+"_median"]=df[var].fillna(median)
        df[var+"_zero"]=df[var].fillna(0)

In [26]:
fillNullColumns(X_train)
X_train.head()

LotFrontage  OverallQual  MasVnrArea  BsmtUnfSF  TotalBsmtSF  1stFlrSF  \
64            NaN            7       573.0        318         1057      1057   
682           NaN            6         0.0        288         1291      1291   
960          50.0            5         0.0        162          858       858   
1384         60.0            6         0.0        356          560       698   
1100         60.0            2         0.0          0          290       438   

      GrLivArea  GarageYrBlt  WoodDeckSF  LotFrontage_median  \
64         2034       1998.0         576                69.0   
682        1291       1996.0         307                69.0   
960         858          NaN         117                50.0   
1384       1258       1939.0           0                60.0   
1100        438       1930.0           0                60.0   

      LotFrontage_zero  MasVnrArea_median  MasVnrArea_zero  \
64                 0.0              573.0            573.0   
682                0.0                0.0              0.0   
960               50.0                0.0              0.0   
1384              60.0                0.0              0.0   
1100              60.0                0.0              0.0   

      GarageYrBlt_median  GarageYrBlt_zero  
64                1998.0            1998.0  
682               1996.0            1996.0  
960               1979.0               0.0  
1384              1939.0            1939.0  
1100              1930.0            1930.0

In [27]:
fillNullColumns(X_test)
X_test.head()

LotFrontage  OverallQual  MasVnrArea  BsmtUnfSF  TotalBsmtSF  1stFlrSF  \
529          NaN            6         NaN        816         2035      2515   
491         79.0            6         0.0        238          806       958   
459          NaN            5       161.0        524          709       979   
279         83.0            7       299.0        768         1160      1156   
655         21.0            6       381.0        525          525       525   

     GrLivArea  GarageYrBlt  WoodDeckSF  LotFrontage_median  LotFrontage_zero  \
529       2515       1975.0           0                70.0               0.0   
491       1578       1941.0           0                79.0              79.0   
459       1203       1950.0           0                70.0               0.0   
279       2022       1977.0         288                83.0              83.0   
655       1092       1971.0           0                21.0              21.0   

     MasVnrArea_median  MasVnrArea_zero  GarageYrBlt_median  GarageYrBlt_zero  
529                0.0              0.0              1975.0            1975.0  
491                0.0              0.0              1941.0            1941.0  
459              161.0            161.0              1950.0            1950.0  
279              299.0            299.0              1977.0            1977.0  
655              381.0            381.0              1971.0            1971.0

In [28]:
X_train_zero=X_train[col_zero]
X_train_zero.head()

LotFrontage_zero  OverallQual  MasVnrArea_zero  BsmtUnfSF  TotalBsmtSF  \
64                 0.0            7            573.0        318         1057   
682                0.0            6              0.0        288         1291   
960               50.0            5              0.0        162          858   
1384              60.0            6              0.0        356          560   
1100              60.0            2              0.0          0          290   

      1stFlrSF  GrLivArea  GarageYrBlt_zero  WoodDeckSF  
64        1057       2034            1998.0         576  
682       1291       1291            1996.0         307  
960        858        858               0.0         117  
1384       698       1258            1939.0           0  
1100       438        438            1930.0           0

In [29]:
X_train_zero.shape

(1022, 9)

In [30]:
X_train_median=X_train[col_median]
X_train_median.head()

LotFrontage_median  OverallQual  MasVnrArea_median  BsmtUnfSF  \
64                  69.0            7              573.0        318   
682                 69.0            6                0.0        288   
960                 50.0            5                0.0        162   
1384                60.0            6                0.0        356   
1100                60.0            2                0.0          0   

      TotalBsmtSF  1stFlrSF  GrLivArea  GarageYrBlt_median  WoodDeckSF  
64           1057      1057       2034              1998.0         576  
682          1291      1291       1291              1996.0         307  
960           858       858        858              1979.0         117  
1384          560       698       1258              1939.0           0  
1100          290       438        438              1930.0           0

In [31]:
X_train_median.shape

(1022, 9)

In [32]:
X_test_zero=X_test[col_zero]
X_test_zero.head()

LotFrontage_zero  OverallQual  MasVnrArea_zero  BsmtUnfSF  TotalBsmtSF  \
529               0.0            6              0.0        816         2035   
491              79.0            6              0.0        238          806   
459               0.0            5            161.0        524          709   
279              83.0            7            299.0        768         1160   
655              21.0            6            381.0        525          525   

     1stFlrSF  GrLivArea  GarageYrBlt_zero  WoodDeckSF  
529      2515       2515            1975.0           0  
491       958       1578            1941.0           0  
459       979       1203            1950.0           0  
279      1156       2022            1977.0         288  
655       525       1092            1971.0           0

In [33]:
X_test_zero.shape

(438, 9)

In [34]:
X_test_median=X_test[col_median]
X_test_median.head()

LotFrontage_median  OverallQual  MasVnrArea_median  BsmtUnfSF  \
529                70.0            6                0.0        816   
491                79.0            6                0.0        238   
459                70.0            5              161.0        524   
279                83.0            7              299.0        768   
655                21.0            6              381.0        525   

     TotalBsmtSF  1stFlrSF  GrLivArea  GarageYrBlt_median  WoodDeckSF  
529         2035      2515       2515              1975.0           0  
491          806       958       1578              1941.0           0  
459          709       979       1203              1950.0           0  
279         1160      1156       2022              1977.0         288  
655          525       525       1092              1971.0           0

In [35]:
X_test_median.shape

(438, 9)

In [36]:
from sklearn.preprocessing import StandardScaler


scaler = StandardScaler()
X_train_zero=scaler.fit_transform(X_train_zero)  
X_test_zero=scaler.transform(X_test_zero)   

In [37]:
X_train_zero

array([[-1.66354382,  0.67840248,  2.59321768, ...,  0.98899634,
         0.28093509,  3.74917535],
       [-1.66354382, -0.05839596, -0.56861686, ..., -0.44659417,
         0.27642211,  1.65308705],
       [-0.19876302, -0.79519441, -0.56861686, ..., -1.28321691,
        -4.22752995,  0.17257858],
       ...,
       [ 0.32855807, -0.05839596, -0.56861686, ...,  0.733952  ,
         0.23580531, -0.73910295],
       [-1.66354382,  0.67840248, -0.46929221, ...,  0.06735883,
         0.29221753,  0.37517448],
       [ 0.03560191,  0.67840248, -0.40307578, ...,  0.61222629,
         0.28093509, -0.73910295]])

In [38]:
X_test_zero

array([[-1.66354382, -0.05839596, -0.56861686, ...,  1.91836248,
         0.22903584, -0.73910295],
       [ 0.65080985, -0.05839596, -0.56861686, ...,  0.10793406,
         0.15231522, -0.73910295],
       [-1.66354382, -0.79519441,  0.31978692, ..., -0.61662374,
         0.17262362, -0.73910295],
       ...,
       [ 1.00235724,  1.41520093,  3.0732868 , ...,  1.14163652,
         0.27416562,  1.09984441],
       [ 0.29926246,  0.67840248,  0.03836709, ...,  0.09827329,
         0.28996105, -0.73910295],
       [ 1.26601779,  2.15199937,  3.62509039, ...,  1.62660721,
         0.30575647, -0.73910295]])

In [39]:
scaler = StandardScaler()
X_train_median=scaler.fit_transform(X_train_median)  
X_test_median=scaler.transform(X_test_median)    

In [40]:
X_train_median

array([[-2.61721241e-02,  6.78402482e-01,  2.59321768e+00, ...,
         9.88996345e-01,  8.20202215e-01,  3.74917535e+00],
       [-2.61721241e-02, -5.83959629e-02, -5.68616856e-01, ...,
        -4.46594173e-01,  7.37916295e-01,  1.65308705e+00],
       [-9.38578417e-01, -7.95194408e-01, -5.68616856e-01, ...,
        -1.28321691e+00,  3.84859781e-02,  1.72578582e-01],
       ...,
       [-7.41935079e-02, -5.83959629e-02, -5.68616856e-01, ...,
         7.33952000e-01, -2.65698175e-03, -7.39102946e-01],
       [-2.61721241e-02,  6.78402482e-01, -4.69292211e-01, ...,
         6.73588253e-02,  1.02591701e+00,  3.75174478e-01],
       [-5.54407346e-01,  6.78402482e-01, -4.03075781e-01, ...,
         6.12226290e-01,  8.20202215e-01, -7.39102946e-01]])

In [41]:
X_test_median

array([[ 0.02184926, -0.05839596, -0.56861686, ...,  1.91836248,
        -0.12608586, -0.73910295],
       [ 0.45404171, -0.05839596, -0.56861686, ...,  0.10793406,
        -1.5249465 , -0.73910295],
       [ 0.02184926, -0.79519441,  0.31978692, ..., -0.61662374,
        -1.15465986, -0.73910295],
       ...,
       [ 1.03029832,  1.41520093,  3.0732868 , ...,  1.14163652,
         0.69677334,  1.09984441],
       [-0.12221489,  0.67840248,  0.03836709, ...,  0.09827329,
         0.98477405, -0.73910295],
       [ 1.46249077,  2.15199937,  3.62509039, ...,  1.62660721,
         1.27277477, -0.73910295]])

In [42]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

### Linear Regression

In [43]:
linreg =LinearRegression()
linreg.fit(X_train_zero,y_train)  
linreg_predict=linreg.predict(X_test_zero)  

print(" Linear Regression MSE for zero : ", format(mean_squared_error(y_test, linreg_predict)))

 Linear Regression MSE for zero :  2162158044.601013


In [44]:
linreg =LinearRegression()
linreg.fit(X_train_median,y_train)  
linreg_predict=linreg.predict(X_test_median)  

print(" Linear Regression MSE for median : ", format(mean_squared_error(y_test, linreg_predict)))

 Linear Regression MSE for median :  2213352533.0368676


MSE değeri küçük olan daha iyi sonuç veriyor. Yani  Nan değerleri 0 ile doldurmak medyan değeri il doldurmaktan daha iyi.